/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        midnight: '#ffffff',
        deepblue: '#f0f9ff',
        darkpurple: '#e0f2fe',
        neon: '#2563eb',
        cyber: '#0ea5e9',
        'bg-light': '#f8fafc',
        'bg-subtle': '#f0f9ff',
        'bg-dark': '#e0f2fe',
        primary: '#2563eb',
        'primary-dark': '#1d4ed8',
        'primary-light': '#60a5fa',
        'primary-subtle': '#eef4ff',
        secondary: '#0ea5e9',
        'secondary-light': '#7dd3fc',
        'secondary-subtle': '#f0f9ff',
        accent: '#3b82f6',
        'accent-light': '#93c5fd',
        'accent-subtle': '#eff6ff',
        warm: '#f59e0b',
        'warm-light': '#fbbf24',
        surface: '#ffffff',
        'surface-secondary': '#f0f9ff',
        'surface-tertiary': '#e0f2fe',
        'surface-hover': '#dbeafe',
        'text-primary': '#1e293b',
        'text-secondary': '#475569',
        'text-tertiary': '#64748b',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      boxShadow: {
        'premium': '0 14px 36px rgba(15,23,42,0.08), 0 0 0 1px rgba(37,99,235,0.06)',
        'premium-md': '0 10px 22px rgba(15,23,42,0.06)',
        'premium-lg': '0 18px 42px rgba(15,23,42,0.08)',
        'premium-xl': '0 28px 70px rgba(15,23,42,0.1)',
        'glow-primary': '0 10px 30px rgba(37,99,235,0.18)',
        'glow-secondary': '0 10px 30px rgba(15,118,110,0.16)',
        'glow-accent': '0 10px 30px rgba(109,40,217,0.16)',
        'card': '0 10px 24px rgba(15,23,42,0.05), 0 0 0 1px rgba(15,23,42,0.04)',
        'card-hover': '0 18px 42px rgba(15,23,42,0.08), 0 0 0 1px rgba(37,99,235,0.08)',
      },
      animation: {
        'float-slow': 'float 8s ease-in-out infinite',
        'float-medium': 'float 6s ease-in-out infinite',
        'float-fast': 'float 4s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 3s ease-in-out infinite',
        'shimmer': 'shimmer 4s ease-in-out infinite',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in': 'fadeIn 0.4s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'spin-slow': 'spin 30s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.6' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        heartbeat: {
          '0%, 100%': { transform: 'scale(1)' },
          '14%': { transform: 'scale(1.05)' },
          '28%': { transform: 'scale(1)' },
          '42%': { transform: 'scale(1.05)' },
          '56%': { transform: 'scale(1)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.92)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'mesh-light': 'radial-gradient(ellipse at 20% 50%, rgba(37,99,235,0.04) 0%, transparent 60%), radial-gradient(ellipse at 80% 20%, rgba(13,148,136,0.03) 0%, transparent 60%), radial-gradient(ellipse at 50% 80%, rgba(109,40,217,0.02) 0%, transparent 60%)',
      },
      backdropBlur: {
        xs: '2px',
        '4xl': '60px',
        '5xl': '80px',
      },
      transitionTimingFunction: {
        'bounce-soft': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'cinematic': 'cubic-bezier(0.65, 0, 0.35, 1)',
        'premium': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
